#!/usr/bin/env bash
# This script loops the display "Best School" for all iterations from 1-10 but on the 4th loop displays "bad luck" and "good luck" for the 8th loop.
i=1

while [ $i -le 10 ]
do
    if [ $i -eq 4 ]; then
        echo "bad luck"
    elif [ $i -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done
