#!/usr/bin/env bash
# This script contains the Highlander

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done

if [ -n "$pid" ]; then
    kill "$pid"
fi
