#!/usr/bin/env bash
# This script contains the Highlander

trap 'echo OK >&2' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done

pid=$(pgrep -f 7-highlander)
if [ -n "$pid" ]; then
    echo "PID of 7-highlander is $pid"
fi
