#!/usr/bin/env bash
# This script displays “Best School” 10 times. However, for the 9th iteration, it displays “Best School” and then, on a new line, displays “Hi”.
i=1

while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]; then
        echo "Hi"
    fi
    i=$((i + 1))
done
